server:
  error:
    include-stacktrace: ALWAYS
  servlet:
    context-path: /
  port: 8001
  address: 0.0.0.0

spring:
  mvc:
    throw-exception-if-no-handler-found: true

# http://1127.0.0.1:8001/actuator/info
info:
  app.name: provider
  company.name: cloud
  build.artifactId: $project.artifactId$
  build.version: $project.version$